// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIM21p0mHSdyxtwxoeIP6wITogBcjG-i0',
    appId: '1:750601970491:web:66f4548bf31d7ab3a58d1e',
    messagingSenderId: '750601970491',
    projectId: 'mindfeed-5f150',
    authDomain: 'mindfeed-5f150.firebaseapp.com',
    storageBucket: 'mindfeed-5f150.firebasestorage.app',
    measurementId: 'G-Z2PQ7CQW62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOWdaRgSoRcXttKlkVG2ZCPSkUxpj1ChA',
    appId: '1:750601970491:android:b051de0e4ac3a081a58d1e',
    messagingSenderId: '750601970491',
    projectId: 'mindfeed-5f150',
    storageBucket: 'mindfeed-5f150.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVx_PcIi1IpGfIBnKmRAVj6VVG11YRglo',
    appId: '1:750601970491:ios:8d128a41f9f64daba58d1e',
    messagingSenderId: '750601970491',
    projectId: 'mindfeed-5f150',
    storageBucket: 'mindfeed-5f150.firebasestorage.app',
    iosBundleId: 'com.example.mindFeed',
  );
}
